### ISSUE TITLE
tilt should warn when yaml has duplicate resources

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#1852]
Repro steps:
1) Add yaml with the same resource twice

```

apiVersion: v1
kind: Service
metadata:
  name: doggos
  labels:
    app: doggos
spec:
  ports:
    - port: 80
      targetPort: 8083
      protocol: TCP
  selector:
    app: doggos
---

apiVersion: v1
kind: Service
metadata:
  name: doggos
  labels:
    app: doggos
spec:
  ports:
    - port: 80
      targetPort: 8083
      protocol: TCP
  selector:
    app: doggos
```

2) Load that yaml in a Tiltfile

```
k8s_yaml('my.yaml')
```

Result:
The Tiltfile fails to load with an error: 
`unable to find a unique resource name for 'doggos:service:default:'`

I think we can all agree that this is a bad and non-helpful error message. But I'm not totally sure what should happen in this case. 

Should it be an error? Should it be a warning? Should Tilt quietly use one of the resources and discard the other one? Something else entirely?
