### ISSUE TITLE
Process for feeding helm template data into k8s_yaml from non-local chart is cumbersome

### ISSUE THREAD

**Issue by bitsofinfo** [tilt-dev/tilt#3030]
a) I need to deploy my app w/ a helm chart in a remote repo

b) it appears I can't just `helm upgrade -- install [mychart] --version x.y.z ....` because tilt only deploys via `k8s_yaml`. I guess i could just via `local()` but then I'm not really leveraging the flow defined by tilt.

c) So I try to `k8s_yaml(local('helm template -f x -f y [chart]`))` but helm2 requires a local chart for `helm template` 

d) In order to do this I have to `helm fetch [remote chart] --untar`, only then can I do `helm template`

This is all very awkward.

Ideally one should just be able to use any helm chart (non-local) to deploy an image that is built by Tilt, and leverage helm to manage it there on out. It appears the only way tilt can deploy things is with raw `k8s_yaml` and only the tilt instance that `tilt up` is monitoring/deployed those manifests can susequently clean them up on `tilt down`. 

What if the dev that deployed all that yaml to k8s via tilt, has their laptop blow up or leaves the company? now the k8s operator has to go track this all down. Being able to fully leverage helm would nicely package up all this stuff into releases that can be managed by others.

**Comment by bitsofinfo** [comment]
#2663

**Comment by nicks** [comment]
Hi @bitsofinfo ! Thanks for the request. Since you also saw https://github.com/windmilleng/tilt/issues/2663, do you see any major differences between that feature request and this one? Or should we consolidate them?

It also sounds like it's important to you that you should be able to manage the installed resources with `helm list` and other `helm` CLI commands, is that right? If you gave us a bit more detail on which helm commands you need to work, that would help us better understand how to address this

**Comment by bitsofinfo** [comment]
i think they are very similar, yes

well I really just want to be able to `helm upgrade --install [any non local chart]` instead of `k8s_yaml` as the only means whereby Tilt can get things onto a cluster (and track it) after a build is triggered... and have Tilt be smart enough to capture the helm `release name` so that on `tilt down` it uses helm under the covers to `helm delete --purge [releasename]`. That  right there seems like it might be something others could use as well.

Secondly, if I could just easily say *"only run these functions on UP but only run these functions on DOWN" etc, then I could just implement this all myself via `locals(mycmd)` however I want (including the build/deploy)

**Comment by bitsofinfo** [comment]
i think they are very similar, yes

well I really just want to be able to `helm upgrade --install [any non local chart]` instead of `k8s_yaml` as the only means whereby Tilt can get things onto a cluster (and track it) after a build is triggered... and have Tilt be smart enough to capture the helm `release name` so that on `tilt down` it uses helm under the covers to `helm delete --purge [releasename]`. That  right there seems like it might be something others could use as well.

Secondly, if I could just easily say *"only run these functions on UP but only run these functions on DOWN" etc*, then the latter paragraph is not needed, I could just implement this all myself via `locals(mycmd)` however I want (including the build/deploy). Just being aware of the UP/DOWN state would open up a much bigger world of functionality to users of Tilt imho. 

If you had that you could even add another state of "RESOURCES CHANGED" etc or something, and include info on what changed... i don't think you are that far from being able to let this just be a fully customizable cicd system for folks w/ an open paradigm.

**Comment by Raboo** [comment]
You could work around the problem by installing the [GitOps Toolkit](https://toolkit.fluxcd.io). It has CRD's for `HelmRepository` and `HelmRelease`.

Used like this
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: chartmuseum
  namespace: flux-system
spec:
  url: https://chartmuseum.github.io/charts
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chartmuseum
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: chartmuseum
      version: "2.14.2"
      sourceRef:
        kind: HelmRepository
        name: chartmuseum
        namespace: flux-system
      interval: 1m
  values:
    env:
      open:
        AWS_SDK_LOAD_CONFIG: true
        STORAGE: amazon
        STORAGE_AMAZON_BUCKET: "bucket-name"
        STORAGE_AMAZON_PREFIX: ""
        STORAGE_AMAZON_REGION: "region-name"
    serviceAccount:
      create: true
      annotations:
        eks.amazonaws.com/role-arn: "role-arn"
    securityContext:
      enabled: true
      fsGroup: 65534
```

This example installs ChartMuseum. 
So you can use a plain YAML to install your helm charts, makes more CI/CD and GitOps friendly.
Check it out, https://toolkit.fluxcd.io/guides/helmreleases/
