### ISSUE TITLE
Error streaming logs when manually triggering a Job (also for deployments?)

### ISSUE THREAD

**Issue by maiamcc** [tilt-dev/tilt#3196]
Reported in #tilt:

> I have a manual trigger resource that needs to update the docker image, live sync, then run and quit.
> ...
> it seems like its working, at least w/ manual trigger, even though it reports an error streaming the job. Maybe that's an error due to killing the previous job instance?
```
STEP 3/3 — Deploying
     Injecting images into Kubernetes YAML
     Applying via kubectl:
     → zope-sync-job:job
     Step 1 - 2.63s
     Step 2 - 0.13s
     Step 3 - 0.14s
     DONE IN: 2.90s 
Error streaming zope-sync-job logs: Get "https://192.168.198.5:16443/api/v1/namespaces/default/pods/zope-sync-job-smztj/log?container=zope-sync-job&follow=true&sinceTime=2020-04-08T17%3A01%3A51Z": context canceled
Tracking new pod rollout (zope-sync-job-tvf59):
     ┊ Scheduled       - <1s
     ┊ Initialized     - <1s
     ┊ Ready           - (…) Pending
2020-04-08 17:01:52,457 root         INFO     sync /app/src/SFI.Zope.Door2Door
```

Note that no logs are being lost here and this is a cosmetic complaint: Tilt is trying to stream logs from a dead pod, and should ideally know better and not spam the user with errors.

I (Maia) want to know if this "error streaming ___ logs" happens consistently or intermittently, and if it happens:
a. when triggering an update for a job that is still running
b. when triggering an update for a job that has completed
c. when triggering an update for a deployment

Also relevant: whether these triggers are full rebuilds (i.e. no files have changed since the last time the resource was built) or if they are releasing pending changes (the resource is in TRIGGER_MODE_MANUAL and some files have been changed since the last build).

A repro case would be especially helpful.

**Comment by bkcsfi** [comment]
Hi,

Its a Job, like this:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: zope-sync-job
  labels:
    app: zope-sync-job
spec:
  template:
    metadata:
      labels:
        app: zope-sync-job
    spec:
      containers:
        - name: zope-sync-job
          image: zope-sync-image
          env:
            - name: ZEO_SERVER
              value: "zeo-server.default.svc.cluster.local.:8100"
      restartPolicy: Never  
```

I am running it with TRIGGER_MODE_MANUAL

It happens  whether or not I have changed any files.

1. the job runs to completion

2. during the run, tilt shows the output from the pod

3. after some time, I manually trigger the resource

4. the image is rebuilt

5. tilt (presumably) tells k8s "please get rid of that previous Job"

6. tilt submits the new Job

7. (guessing) some thread in Tilt is still watching the output from the previous Job that is being removed

8. The previous job is removed from k8s, Tilt reports `Error streaming zope-sync-job logs: Get "https://192.168.198.5:16443/api/v1/namespaces/default/pods/zope-sync-job-smztj/log?container=zope-sync-job&follow=true&sinceTime=2020-04-08T17%3A01%3A51Z": context canceled
`

9. Tilt starts watching the output from the new Job `Tracking new pod rollout (zope-sync-job-tvf59)`

I think this is a cosmetic issue. If tilt knows the pod is going to go away (because it's planning to deploy a new one), maybe it can set a flag so the previous watching thread can know not to report the `context canceled` error because it's expected.
