### ISSUE TITLE
helm() function overwrites namespace

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3349]
Repro steps:
1) Create a namespace like

```
apiVersion: v1
kind: Namespace
metadata:
  name: alice
  labels:
    argocd.argoproj.io/instance: alice
```

2) Apply that namespace outside of Tilt
3) Add helm(..., namespace='alice') to your Tiltfile

Expected result:
Tilt uses the existing namespace

Actual result:
Tilt overwrites the namespace

```
apiVersion: v1
kind: Namespace
metadata:
  name: alice
  labels:
    app.kubernetes.io/managed-by: tilt
```

This interferes with other tools, and is different than how Helm works. Reported in the tilt channel
