### ISSUE TITLE
knative errors when using tilt

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3419]
In the #tilt channel, Munjal reports that they're getting these errors reported as events:

```
[K8s EVENT: Revision svc-data-twitter-lrxc8 (ns: default)] failed to update deployment "svc-data-twitter-lrxc8-deployment": Operation cannot be fulfilled on deployments.apps "svc-data-twitter-lrxc8-deployment": the object has been modified; please apply your changes to the latest version and try again
[K8s EVENT: Route svc-data-twitter (ns: default)] failed to update Ingress: Operation cannot be fulfilled on ingresses.networking.internal.knative.dev "svc-data-twitter": the object has been modified; please apply your changes to the latest version and try again
```

Here is the Tiltfile:

```
k8s_kind('Service', api_version='serving.knative.dev/v1',
         image_json_path='{.spec.template.spec.containers[].image}')
npm_token = decode_yaml(local('cat ~/.npmrc')).split('=')[1]
docker_build('dev.local/svc-data-twitter', '.', build_args={'NPM_TOKEN': npm_token})
k8s_yaml(kustomize('.'))
k8s_resource('svc-data-twitter', port_forwards=5601)
```

and k8s yaml:

```
apiVersion: v1
data:
  TWITTER_TOKEN_KEY: base64-string
  TWITTER_TOKEN_SECRET: base64-string
kind: Secret
metadata:
  name: svc-data-twitter
  namespace: default
type: Opaque
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    serving.knative.dev/visibility: cluster-local
  name: svc-data-twitter
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - env:
        - name: TWITTER_TOKEN_KEY
          valueFrom:
            secretKeyRef:
              key: TWITTER_TOKEN_KEY
              name: svc-data-twitter
        - name: TWITTER_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              key: TWITTER_TOKEN_SECRET
              name: svc-data-twitter
        image: dev.local/svc-data-twitter
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:5601
          initialDelaySeconds: 10
        ports:
        - containerPort: 5601
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:5601
          initialDelaySeconds: 5
```

They also note:

> I am using Kubernetes that comes with Docker in my Macbook. I also have demo profile of Istio and Knative configured in my cluster

This might be related to https://github.com/tilt-dev/tilt/issues/3232
