### ISSUE TITLE
image injection is unaware of image_json_path

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3460]
e.g., create an instance of a CRD like this:
```
apiVersion: openfaas.tilt.dev/v1alpha1
kind: Function
metadata:
  name: addone
  namespace: openfaas-fn
spec:
  image: addone
```

and define a docker_build for `addone`

specify `k8s_kind('Function', image_json_path="{.spec.image}")` in your Tiltfile

The Tilt code for injecting into instances of CRDs just replaces the image name [anywhere it finds it](https://github.com/windmilleng/tilt/blob/5d5545054425dfb4f00e8f9a61bd039680062904/internal/k8s/image.go#L168), even though the Tiltfile says where the image is.

This results in .metadata.name being replaced with something like addone:tilt-12323435456, which makes it illegal. It also opens us up to incorrectly replacing other fields where the bug would not be so immediately apparent.

We should propagate the image_json_path to the image injector and only replace things at that path.

originally filed by @landism , rediscovered today when people were experimenting with knative in the tilt channel
