### ISSUE TITLE
Syncing live_update with multiple / derivative images?

### ISSUE THREAD

**Issue by Kezzsim** [tilt-dev/tilt#3502]
I have a Loopback/Express.js project that builds one container as a base with all methods specified:
(_./app/Dockerfile_)
```
FROM node:10-slim
COPY --chown=node . .
## other build instructions ##
```
And then builds derivative images by calling that as the baseimage, with the contents of the `server` folder overrided with different configurations from that context:
(_./subservice1/Dockerfile_)
```
FROM thisproject_core:latest
COPY --chown=node . ./server
## other build instructions ##
```
Combined into a docker-compose.yml, the result is something like this, where _core_ is the first Dockerfile and subservice1 & 2 are products of the later:
```
  core:
    image: thisproject_core
    build: './app'
    container_name: core
  subservice1:
    image: thisproject_subservice1
    build: './subservice1'
    container_name: subservice1
  subservice2:
    image: thisproject_subservice2
    build: './subservice1'
    container_name: subservice2
```
This is all fine and dandy and I can add a `live_update` sync path to watch the subservice folders with no problems. However, what if I need multiple sync paths? Because each time I update the main _core_ image, the subservices should pull in those changes and restart.

I've tried doing this:
```
docker_compose("./docker-compose.yml")
docker_build('thisproject_core', './app', live_update = [
    sync('./app', '/home/node/app'),
    run('npm i', trigger='package.json'),
    restart_container()
])
docker_build('thisproject_subservice1', './subservice1', live_update = [
    sync('./app', '/home/node/app'),
    sync('./subservice1', '/home/node/app/server'),
    restart_container()
])
```
Such that both `docker_builds` are watching ./app for changes... but that results in this error:
```
sync step source '/Users/kezz/Desktop/thisproject/app' is not a child of any watched filepaths ([/Users/kezz/Desktop/thisproject/subservice1])
```
Is the implication that the sync path is limited by docker's build context? I mean, that's alright but then I have to find a way to rebuild the core image whenever I make a change so the derivative containers can pick it up... 
Let me know if there's any known workarounds for this, it's really cool that Docker can re-use images to cut down on resources when building similar replicas, it would be great to tap into that with tilt!
