### ISSUE TITLE
Internal error occurred: Authorization error

### ISSUE THREAD

**Issue by dealancer** [tilt-dev/tilt#3547]
I am seeing following error message for all containers run with Tilt. Not sure if it is Tilt or a Kubernetes problem:

```
Error streaming web-deployment logs: Internal error occurred: Authorization error (user=kube-apiserver-kubelet-client, verb=get, resource=nodes, subresource=proxy)
```

I am using recent version of the Tilt and Kubernetes.

**Comment by nicks** [comment]
Googling around a bit, this error means that Kubernetes itself is having problems fetching logs because the permissions are set up incorrectly:
https://github.com/kubernetes/kops/issues/5706
https://stackoverflow.com/questions/54572775/kubectl-logs-f-gets-authorization-error

i.e., using `kubectl logs -f [YOUR POD]` would also fail with this error

The github ticket suggests adding this ClusterRoleBinding

```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubelet-api-admin
subjects:
- kind: User
  name: kubelet-api
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: system:kubelet-api-admin
  apiGroup: rbac.authorization.k8s.io
```

does that help?
