### ISSUE TITLE
[Feature Request] Assign prefix/namespace to imported Tiltfiles

### ISSUE THREAD

**Issue by kevin-lindsay-1** [tilt-dev/tilt#3587]
I have `Tiltfile`s that are generally very similar, and designed to work in isolation, and I am now attempting to compose them. 

Unfortunately, I have resource definitions that use the same naming convention, and as a result I now need to manually add prefixes to them in order to prevent namespace collisions.

I am going to double-check the docs to make sure I'm using the correct implementation methodology, but if I find that this particular use case isn't documented/handled, then I'd say this would be a valuable feature to have.

**Comment by maiamcc** [comment]
Neat idea! As far as I know, the closest thing to what you're requesting is the ability of `load` to reassign loaded values: see [the Starlark spec](https://github.com/bazelbuild/starlark/blob/master/spec.md#load-statements). Will this work for your use case?

**Comment by kevin-lindsay-1** [comment]
To get something akin to namespacing, it looks like I'd have to manually `load` and assign a value to each variable I'd like to import, which appears to be passed by value, not by reference (not 100% sure though).

For example, I'd be looking for something like this:
```
dependencies = [
  ['namespace1', './namespace1/Tiltfile'],
  ['namespace2', './namespace2/Tiltfile'],
  ...
]

for dependency in dependencies:
  namespace = dependency[0]
  tiltfilePath = dependency[1]
  load(
    tiltfilePath,
    resourceNameToOverride = 'resourceNameToOverride'
  )
  resourceNameToOverride = '{}-resourceNameToOverride'.format(namespace)
```

which would preferably result in something like:
```
resources = [
  'resourceNameToOverride', # local project, no namespace in this context
  'namespace1-resourceNameToOverride',
  'namespace2-resourceNameToOverride',
  ...
]
```

Additionally, it would be really nice if Tilt was capable of grouping these namespaced resources instead of putting them all in the same line. e.g.:
```
resources:
  - install deps (local)
  - build (local)
  - service (docker_build/k8s_resource)
  - namespace1:
       resources:
         - install deps (local)
         - build (local)
         - service (docker_build/k8s_resource)
  - namespace2:
       resources:
         - install deps (local)
         - build (local)
         - service (docker_build/k8s_resource)  
```

So that you could collapse things such as:
```
resources:
  - install deps (local)
  - build (local)
  - service (docker_build/k8s_resource)
  - namespace1
  - namespace2
```
