### ISSUE TITLE
Mapped port-forwards don't seem to work

### ISSUE THREAD

**Issue by KOGI** [tilt-dev/tilt#3638]
```python
k8s_resource('blah', port_forwards=[80])      # works 🥳
k8s_resource('blah', port_forwards=['80'])    # works 🎉
k8s_resource('blah', port_forwards=80)        # works 🌈
k8s_resource('blah', port_forwards='80')      # works ✨
k8s_resource('blah', port_forwards=['80:80']) # doesn't work 😢
k8s_resource('blah', port_forwards='80:80')   # doesn't work 😢
```

deployed k8s service:
```
...snip...
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32123
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
      nodePort: 30050
```
