### ISSUE TITLE
Duplicate YAML Entries when calling `helm()`

### ISSUE THREAD

**Issue by KOGI** [tilt-dev/tilt#3656]
This behavior seems to have started with Tilt v0.17.0. I originally thought it was related to the `helm_remote()` extension, but have since traced it back to Tilt itself (via `helm()`).

### Problem:
```
Tilt started on http://localhost:10350/
v0.17.0, built 2020-07-31

Initial Build • (Tiltfile)
Beginning Tiltfile execution
Running: [helm template chart /path/to/helmchart --include-crds]
Successfully loaded Tiltfile (373.0113ms)
Duplicate YAML  #Entity:
certgen:serviceaccount:default:core has been detected across one or more resources.
Only one specification per entity can be applied to the cluster;
to ensure expected behavior, remove the duplicate specifications.
```

* This is attempting to install a local copy of the raw helmchart directly from the [repo](https://storage.googleapis.com/solo-public-helm).
* No modifications have been made to the helmchart whatsoever.
* This is the _only_ command in the Tiltfile

### Reproduce Steps:

1. run  
`helm repo add gloo https://storage.googleapis.com/solo-public-helm && helm pull gloo/gloo --untar --destination /path/to/helmcharts`
1. create a Tiltfile with the following contents:  
`k8s_yaml(helm('/path/to/helmcharts/gloo'))`
1. run  
`tilt up`

### Additional Thoughts
It would be super helpful if the above error message were to tell the user where these duplicates were found. This would allow us to much more easily locate a problem in our tiltfile.

**Comment by jazzdan** [comment]
Hmm, yeah this is working as intended because that chart _does_ define `certgen:serviceaccount:default:core` twice:

```
# Source: gloo/templates/6.5-gateway-certgen-job.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "5" # must be executed before cert-gen job
  name: certgen
  namespace: default
  
---

# Source: gloo/templates/6.5-gateway-certgen-job.yaml
# Resources created as hooks are not considered part of a release by Helm. This means that they
# will not be cleaned up when running `helm uninstall`. The ways to get around this are documented here:
# https://helm.sh/docs/topics/charts_hooks/#hook-resources-are-not-managed-with-corresponding-releases).
# These will not work for us though: we can't use `hook-delete-policy` since we have multiple hooks that depend
# on each other (RBAC resources needed by the job), and we cannot write a job to clean them up as this would result
# in a catch-22 (this second job would in turn need its own RBAC resources and who would clean up those?).
#
# To be able to clean up these hook resources, which are needed only temporarily during the pre-install phase,
# we redefine them as `post-install` hooks with a `hook-delete-policy`. This way Helm will reapply them and
# immediately delete them after the installation completes. Note that we have to explicitly define a `before-hook-creation`
# policy as well, to avoid failing on existing resources (`before-hook-creation` is the default `hook-delete-policy`
# if none is specified`).
#
# The following resources implement this workaround.
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "solo.io/hook-cleanup": "true" # Used internally to mark "hook cleanup" resources
  name: certgen
  namespace: default
```
If I'm reading that comment on the second one correctly this may be due to some work that this chart is doing to get around some limitations in Helm's hook functionality.

My first thought if we could use [`filter_yaml`](https://docs.tilt.dev/api.html#api.filter_yaml) to filter out the duplicate one. Unfortunately the fact that these two resources differ only by their annotations makes this hard.

My next thought was that we could somehow manually remove the duplicate by using `filter_yaml` to select the duplicates and then removing one of them.

```Tiltfile
orig = helm('gloo')
tofilter, rest = filter_yaml(helm('gloo'), name='certgen', kind='ServiceAccount')
k8s_yaml(rest)

yaml = decode_yaml_stream(tofilter)
# drop one of them
certgen = yaml[0]
k8s_yaml(encode_yaml(certgen))
```

Unfortunately then there's another duplicate entry, and I stopped here for the day.

```
Duplicate YAML Entity: gloo-gateway-validation-webhook-default:validatingwebhookconfiguration:default:admissionregistration.k8s.io has been detected across one or more resources.  Only one specification per entity can be applied to the cluster; to ensure expected behavior, remove the duplicate specifications.
```

Maybe there should be a way for you to opt in and "ignore duplicates"? Let me think about this:

>It would be super helpful if the above error message were to tell the user where these duplicates were found. This would allow us to much more easily locate a problem in our tiltfile.

Agreed. @abdullahzameek do you have any thoughts on how we would surface this?
