### ISSUE TITLE
extra_pod_selectors for k8s_kind

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3717]
A common pattern in CRDs is to have a CR that looks like this:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-world
  namespace: argo
```

which creates pods that look like this:

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/workflow: hello-world
```

Currently, Tilt has a hard time finding these pods, because they don't inherit the labels of their owner (and tilt is looking for the managed-by: tilt label)

We currently work around this by having extra_pod_selectors at the k8s_resource level, as described here:
https://docs.tilt.dev/custom_resource.html

But what you really want in this case is extra_pod_selectors at the k8s_kind level, like:

```
k8s_kind('workflow', extra_pod_selectors={'workflows.argoproj.io/workflow': '{.metadata.name}'})
```

where the value is a JSON spec pointing to the Custom resource

I can think of other ways you might do this (and TBH I think we're eventually going to need to write a library of k8s_kinds for common CRDs), but this seems like a good start.
