### ISSUE TITLE
Fully qualified object selector doesn't work

### ISSUE THREAD

**Issue by samwyma** [tilt-dev/tilt#3813]
Hi! 

We've started using Tilt recently and so far are loving it. We have a small bug in the way resources are referenced via object selectors. It [says in the docs](https://docs.tilt.dev/tiltfile_concepts.html#configuring-kubernetes-resources) that you can optionally provide a more qualified object selector for an object, but this doesn't seem to be the case.

Here is an example Tiltfile:

```
k8s_yaml(blob("""
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
"""))

k8s_resource("nginx-deployment-2:deployment:default", resource_deps=["nginx-deployment-1"])
```

If I'm understanding the docs correctly, the k8s_resource command should run fine with the fully qualified selector, but Tilt is throwing an error for me. 

I'm on Tilt v0.17.5.

Cheers!
