### ISSUE TITLE
mysterious warnings on kubernetes <= 1.14

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3870]
If you try to use Tilt with Kubernetes <= 1.14, you get mysterious warnings like this:

> W1020 18:23:54.425957  177752 reflector.go:424] tilt/internal/k8s/watch.go:336: watch of *v1.PartialObjectMetadata ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: no kind \"ReplicaSet\" is registered for version \"apps/v1\" in scheme \"k8s.io/apimachinery/pkg/apis/meta/internalversion/scheme/register.go:27\"") has prevented the request from succeeding

I strongly suspect this is related to the way we use the metadata informer, which is supposed to polyfill some behavior for old kubernetes versions, but doesn't seem to be working correctly.

**Comment by nicks** [comment]
something really weird is happening with how kubernetes is doing api versioning internally

I'm seeting resources that look like this:

```
apiVersion: extensions/v1beta1
  kind: ReplicaSet
  metadata:
    name: busybox1-5959476b97
    ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: busybox1
      uid: 929ca805-1326-11eb-9e3c-0242274dee52
```

where, e.g., the owner reference says it's v1 but the apiVersion of the resource itself is extensions/v1beta1
