### ISSUE TITLE
dynamically set trigger_mode

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#4198]
Mehran prs in the #tilt channel asks

> [if there's a way] to check if a resource named example-deploy  exist, set its trigger_mode

When I asked for more detail, they wrote:

> My Tiltfile gets a config file, in that config file we define what resources need to be enabled in each microservice, each microservice has a helm chart that contains some deployments (usually 3 or 2), now I need to check if my config file contains invalid resource name, do not call to other methods in my Tiltfile, but seems we should be careful and don't have any wrong resource name in our config file.
> example of config file:

```
apps:
  - name: accounting
    enabled: true
    build_img: false
    resources:
      accounting-grpc:
        enabled: true
        trigger_mode: TRIGGER_MODE_MANUAL
      accounting-worker:
        enabled: true
        trigger_mode: TRIGGER_MODE_MANUAL
```

I thought this was a great articulation of a problem I've seen with other teams - the ability to more dynamically set whether a resource auto-builds, without necessarily knowing in advance that you're going to be building that resource during this session
