### ISSUE TITLE
The "create_namespace=True" option of helm_remote deletes the namespace in combination with a Strimzi problem

### ISSUE THREAD

**Issue by ManuelNeubergerWN** [tilt-dev/tilt#4377]
### Expected Behavior
Namespaces should not be deleted from the Tiltfile, even if some helm chart fails.

### Current Behavior
The namespace is deleted from Tilt if the reload button is pressed. This only happens in combination with a certain Strimzi configuration as far as I can tell.

### Steps to Reproduce
1. Create a Tiltfile and yaml file like the following (the Kafka resource must contain some resources which are too high for Strimzi):

```
allow_k8s_contexts("YourCluster")
load('ext://helm_remote', 'helm_remote')
if config.tilt_subcommand != 'down':
  helm_remote('strimzi-kafka-operator', repo_url='https://strimzi.io/charts/', repo_name='strimzi', namespace="kafka", create_namespace=True)
k8s_resource("strimzi-cluster-operator", resource_deps=["uncategorized"])
k8s_kind('Kafka')
k8s_yaml('kafka-cluster.yaml')
k8s_resource(
    workload = "kafka-cluster",
    extra_pod_selectors = {
        "strimzi.io/cluster": "kafka-cluster",
        "strimzi.io/kind": "Kafka",
    },
   resource_deps = ["strimzi-cluster-operator"],
)
```

kafka-cluster.yaml: 
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: telematics-cluster
  namespace: kafka
spec:
  kafka:
    version: 2.6.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: internal1
        port: 9093
        type: internal
        tls: false
    resources:
      requests:
        memory: 64Gi
        cpu: "8"
      limits:
        memory: 64Gi
        cpu: "12"
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
      class: default-hdd-retain
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
2. Tilt up!
3. "uncategorized" will throw an error -> "Updating kafkas.kafka.strimzi.io failed. Attempting to delete + recreate: CustomResourceDefinition.apiextensions.k8s.io "kafkas.kafka.strimzi.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes". This error is caused by some Strimzi problem (sofar it is correct behavior that tilt fails).
4. Press "force an update on this resource" on "uncategorized" -> Tilt fails again but this time the namespace is deleted!!!

#### `tilt doctor` Output
Tilt: v0.19.1, built 2021-03-26
System: windows-amd64
---
Docker
- Host: [default]
- Version: 1.41
- Builder: 2
---
Kubernetes
- Env: unknown
- Context: context
- Cluster Name: cluster-name
- Namespace: default
- Container Runtime: containerd
- Version: v1.20.2
- Cluster Local Registry: none

#### About Your Use Case
We are using Tilt too quickly setup a Kafka environment.

#### Obervations
It seems this problem comes from a little problem in Strimzi and a little problem in Tilt, but in combination, they can be very harmful (as a namespace is deleted).
An easy workaround is to remove "create_namespace=True" from "helm_remote", but of course, it still should be fixed.
