### ISSUE TITLE
tilt down should handle missing crds

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#4519]
### Steps to Reproduce
Tiltfile:

```
k8s_yaml('crd.yaml')
k8s_yaml('crontab.yaml')
```

crd.yaml:

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
```

crontab.yaml:

```
apiVersion: "stable.example.com/v1"
kind: CronTab
metadata:
  name: my-new-cron-object
spec:
  cronSpec: "* * * * */5"
  image: my-awesome-cron-image
```

Run `tilt down`

### Expected Behavior
Tilt should gracefully delete all resources, ignoring "not found" errors

### Current Behavior
Error: Deleting k8s entities: kubernetes delete: unable to recognize "": no matches for kind "CronTab" in version "stable.example.com/v1"
