### ISSUE TITLE
Handle K8s Jobs with BackoffLimitExceeded

### ISSUE THREAD

**Issue by milas** [tilt-dev/tilt#4788]
Tilt does not currently have any special handling for `Job`s in K8s. To determine its runtime status, we look at the associated `Pod`s.

In general, this works - if the `Pod` fails, the `Job` shows as being in error. If the `Job` has hit its `backoffLimit`, the final `Pod` will be the one Tilt is looking at and using to determine that it's failed.

However, if the `Job` container has `RestartPolicy: OnFailure`, the `job-controller` will actually _delete_ the `Pod` once `backoffLimit` is hit to prevent it from continuing to execute more times! As a result, there's no longer a `Pod` for Tilt to examine and so it thinks the `Job` is perpetually in a Pending state.

To catch this case, Tilt would need to discover/track `Job` objects vs just `Pod`s and look at the `Job` status:
```yaml
status:
  conditions:
  - lastProbeTime: "2021-07-22T17:18:40Z"
    lastTransitionTime: "2021-07-22T17:18:40Z"
    message: Job has reached the specified backoff limit
    reason: BackoffLimitExceeded
    status: "True"
    type: Failed
```

This might have some substantial ripple effects to the Tilt runtime tracking code, so might not be totally feasible. I can also imagine that there are CRDs out there which would suffer from similar issues - perhaps what we really need is a way to customize how Tilt determines runtime status for a K8s entity?
