### ISSUE TITLE
disabled buttons broken at master

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#4954]
button.yaml

```
apiVersion: tilt.dev/v1alpha1
kind: UIButton
metadata:
  name: sample
spec:
  text: sample
  disabled: true
  location:
    componentType: resource
    componentID: "(Tiltfile)"
  inputs:
  - name: example
    label: example
    bool: {}
 ```

```
tilt apply -f button.yaml
```

Output:
![Screenshot from 2021-09-10 12-30-49](https://user-images.githubusercontent.com/278641/132887790-eda708fd-ec02-4c07-ad76-c09cfee53386.png)
