### ISSUE TITLE
add links to dynamically allocated docker ports

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#4998]
Create a docker-compose.yaml file:

```
version: '3.7'
services:
  tomcat:
    image: tomcat:8-slim
    ports:
      - "8080"
```

with the Tiltfile:

```
docker_compose('docker-compose.yml')
```

## What Currently Happens:
Docker exposes port 8080 of the container on a randomly allocated port on the host machine.

Tilt does not know it exists and doesn't display it anywhere in the Tilt UI

## What Actually Happens:
Tilt should detect the dynamically allocated host port and display a link to it.
