### ISSUE TITLE
spec.volumes missing in tilt generated kubernets yaml

### ISSUE THREAD

**Issue by lsascha** [tilt-dev/tilt#5063]
### Expected Behavior
correctly create volumes for a kubernetes deployment.

### Current Behavior
Error in deploying an app with a mounted configmap.
`Deployment.apps "multicontainer" is invalid: spec.template.spec.containers[1].volumeMounts[0].name: Not found: "multicontainer-nginx-config-volume"`

### Steps to Reproduce
1. Create a kubernetes yaml with a configmap and deployment
2. have that configmap mounted into a container inside the deployment
3. see tilt generated yaml with `tilt get kubernetesapply -o yaml` to see the missing `volumes:` part in the yaml
4. example project files here: https://gist.github.com/lsascha/2257de736c49499e88c1fc40faee4cfb

#### `tilt doctor` Output

```
Tilt: v0.22.11, built 2021-10-01
System: linux-amd64
---
Docker
- Host: [default]
- Server Version: 20.10.9
- API Version: 1.41
- Builder: 2
- Compose Version: v1.23.1 (build b02f1306)
---
Kubernetes
- Env: kind-0.6+
- Context: kind-kind
- Cluster Name: kind-kind
- Namespace: default
- Container Runtime: containerd
- Version: v1.21.1
- Cluster Local Registry: {Host:localhost:5000 hostFromCluster: SingleName:}
---
...
```

#### About Your Use Case
Trying to setup a local development environment for our projects, which are all multi-container environments. All tilt examples i found on the website are single-container examples and never use any volumes.

**Comment by nicks** [comment]
Kubernetes is telling you that your Deployment sepc is invalid.

In particular, deployment.spec doesn't have a "volumes" field. You need to use seployment.spec.template.spec.volumes

i.e.,

```
spec:
  volumes:
    - name: multicontainer-nginx-config-volume
      configMap:
        name: multicontainer-nginx-configmap
  template:
    ...
```

should be:

```
spec:
  template:
    spec:
      volumes:
        - name: multicontainer-nginx-config-volume
          configMap:
            name: multicontainer-nginx-configmap
```

Let us know if that works...i wonder if we should add some additional validation to the applier...
