### ISSUE TITLE
Tiltfile API resource's labels are not duplicated to its UIResource counterpart

### ISSUE THREAD

**Issue by fhuitelec** [tilt-dev/tilt#5100]
### Expected Behavior

When creating a [Tiltfile](https://api.tilt.dev/core/tiltfile-v1alpha1.html#Tiltfile) API resource with `metadata.labels`, they should<sup>1</sup> be duplicated into the Tiltfile's derived `UIResource`.

<details><summary>In the UI...</summary><p>

<img src="https://user-images.githubusercontent.com/6122860/139504792-0864b9cf-4f2f-44ec-827e-20854c5adbb6.png" data-canonical-src="https://user-images.githubusercontent.com/6122860/139504792-0864b9cf-4f2f-44ec-827e-20854c5adbb6.png" width="225" />

</p></details>

### Current Behavior

The `UIResource` does not have labels the `Tiltfile` and is marked _unlabeled_ in the UI.

<details><summary>In the UI...</summary><p>

<img src="https://user-images.githubusercontent.com/6122860/139504785-93d92268-9639-4c5a-89e0-805b0ac0105a.png" data-canonical-src="https://user-images.githubusercontent.com/6122860/139504785-93d92268-9639-4c5a-89e0-805b0ac0105a.png" width="225" />

</p></details>

### Steps to Reproduce

1. <details><summary>Apply a Tiltfile API resource with a label:</summary><p>

    ```shell
    cat <<EOF | tilt apply -f -
    apiVersion: tilt.dev/v1alpha1
    kind: Tiltfile
    metadata:
      labels:
        Tiltfile-label: Tiltfile-label
      name: (Tiltfile service)
    spec:
      path: /some/path
    EOF
    ```

</p></details>

2. Let it appear _unlabeled_ in the UI

3. <details><summary>Check the Tiltfile has, indeed, labels:</summary><p>

    ```shell
    tilt get tiltfile '(Tiltfile service)' -o yaml
    ```
    ```yaml
    apiVersion: tilt.dev/v1alpha1
    kind: Tiltfile
    metadata:
      name: (Tiltfile service)
      labels:
        Tiltfile-label: Tiltfile-label
    spec: {} # [...]
    status: {} # [...]
    ```
</p></details>

4. <details><summary>Check the derived UIResource:</summary><p>

    ```shell
    tilt get uiresource '(Tiltfile service)' -o yaml
    ```
    ```yaml
    apiVersion: tilt.dev/v1alpha1
    kind: UIResource
    metadata:
      # No labels 😏
      name: (Tiltfile service)
    spec: {} # [...]
    status: {} # [...]
    ```

</p></details>

### Context

<details><summary>tilt doctor output</summary><p>

```shell
tilt doctor
# > Tilt: v0.22.14, built 2021-10-22
# > System: linux-amd64
# > ---
# > Docker
# > - Host: [default]
# > - Server Version: 20.10.8
# > - API Version: 1.41
# > - Builder: 2
# > - Compose Version: v1.29.2 (build 5becea4c)
# > ---
# > Kubernetes
# > - Env: none
# > - Context: 
# > - Cluster Name: Unknown
# > - Namespace: default
# > - Container Runtime: unknown
# > - Version: Error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
# > - Cluster Local Registry: none
# > ---
```

</p></details>

#### About Your Use Case

I'm in the midst of creating a simple dependency manager Tilt extension (not yet submitted in tilt-dev/tilt-extensions).

In this context, I need to create Tiltfile resources<sup>2</sup>.

For those Tiltfiles, I want the UI to visually help the user:
- to group and hide this kind of resources
- to know where to find them intuitively
- to extend the current extension naming standard, eg. `extension.dependency.tiltfiles`

And labels seem perfect for these needs.

Note I am aware [TiltfileSpec](https://api.tilt.dev/core/tiltfile-v1alpha1.html#TiltfileSpec) exposes a `labels` attribute but I only want to group the Tiltfile resources and not the Tiltfile child resources.

---

<sup>1</sup> Sorry, that's a bit opinionated :sweat_smile:
<sup>2</sup> BTW, I love the ongoing efforts towards a public API
