### ISSUE TITLE
runtime status shows as pending for manual, non-auto-init resources

### ISSUE THREAD

**Issue by lizzthabet** [tilt-dev/tilt#5295]
[Reported by Tim Loyer in k8s slack](https://kubernetes.slack.com/archives/CESBL84MV/p1639673609051500).

### Expected Behavior
K8s resources with `auto_init=False` and `TRIGGER_MODE_MANUAL` should not have a runtime status marked as pending when they load in the UI dashboard. Instead, they should have a `No server` indication. They should not be included in the resource status summary count. 

Here's a `UIResource` status during the expected case (testing with Tilt's www site):
```yaml
status:
  disableStatus:
    disabledCount: 0
    enabledCount: 1
    sources:
    - configMap:
        key: isDisabled
        name: tilt-site-disable
  endpointLinks:
  - name: tilt-site
    url: http://localhost:4000/
  hasPendingChanges: true
  lastDeployTime: null
  order: 2
  pendingBuildSince: "2021-12-16T20:22:55.570467Z"
  runtimeStatus: not_applicable
  specs:
  - id: image:tilt-site-base
    type: image
  - hasLiveUpdate: true
    id: image:tilt-site
    type: image
  - id: k8s:tilt-site
    type: k8s
  triggerMode: 2
  updateStatus: none
```

![image (2)](https://user-images.githubusercontent.com/23283986/146451310-0f3e524b-85e4-4ab9-94fd-d23cdae43699.png)

### Current Behavior
Resources have a runtime status marked as pending and show up in the status summary as pending.

![image (1)](https://user-images.githubusercontent.com/23283986/146449839-48f413ff-72c4-489f-9188-4ec73e6521de.png)

![image](https://user-images.githubusercontent.com/23283986/146449846-7d346950-425a-48c6-9d6b-b64abb29c182.png)
(Screenshots pulled from k8s slack)

Here's the same `UIResource` status with the incorrect pending display:
```yaml
status:
  conditions:
  - lastTransitionTime: "2021-12-16T20:31:43.497605Z"
    reason: Unknown
    status: "False"
    type: UpToDate
  - lastTransitionTime: "2021-12-16T20:31:43.497605Z"
    reason: Unknown
    status: "False"
    type: Ready
  disableStatus:
    disabledCount: 0
    enabledCount: 1
    sources:
    - configMap:
        key: isDisabled
        name: tilt-site-disable
  endpointLinks:
  - name: tilt-site
    url: http://localhost:4000/
  hasPendingChanges: true
  k8sResourceInfo:
    podCreationTime: null
    podUpdateStartTime: null
  lastDeployTime: null
  order: 2
  pendingBuildSince: "2021-12-16T20:31:47.078431Z"
  runtimeStatus: pending
  specs:
  - id: image:tilt-site-base
    type: image
  - hasLiveUpdate: true
    id: image:tilt-site
    type: image
  - id: k8s:tilt-site
    type: k8s
  triggerMode: 2
  updateStatus: none
```

### Steps to Reproduce

1. Use a `Tiltfile` that includes a manual, non-init'd resource
2. `tilt up` using >= v0.23.2

### Context
Running through a `git bisect`, I found that [c531e05](https://github.com/tilt-dev/tilt/commit/c531e05e1eec10984f785be0802efcb95fd6e61a) (introduced in #5234) was the first time I noticed this issue.
