### ISSUE TITLE
Failed to pull image connection refused

### ISSUE THREAD

**Issue by maximegel** [tilt-dev/tilt#5431]
### Current Behavior

It seems like the K8s pod is unable to pull images at localhost:5000.

```console
[K8s EVENT: Pod brokerage-api-848db55948-9pg9n (ns: default)] Pulling image "localhost:5000/brokerage-api:tilt-b655dbb021099edd"
[K8s EVENT: Pod brokerage-api-848db55948-9pg9n (ns: default)] Failed to pull image "localhost:5000/brokerage-api:tilt-b655dbb021099edd": rpc error: code = Unknown desc = failed to pull and unpack image "localhost:5000/brokerage-api:tilt-b655dbb021099edd": failed to resolve reference "localhost:5000/brokerage-api:tilt-b655dbb021099edd": failed to do request: Head "http://localhost:5000/v2/brokerage-api/manifests/tilt-b655dbb021099edd": dial tcp 127.0.0.1:5000: connect: connection refused
[K8s EVENT: Pod brokerage-api-848db55948-9pg9n (ns: default)] Error: ErrImagePull
[K8s EVENT: Pod brokerage-api-848db55948-9pg9n (ns: default)] Error: ImagePullBackOff
```

### Steps to Reproduce
The code can be found here: https://github.com/maximegel/stock-trader/tree/bazel

1. `ctlptl apply -f ./devcluster.yaml`
2. `tilt up`

#### `tilt doctor` Output

```
$ tilt doctor
Tilt: v0.23.5, built 2022-01-07
System: linux-amd64
---
Docker
- Host: [default]
- Server Version: 20.10.11+azure-3
- API Version: 1.41
- Builder: 2
- Compose Version: v1.29.2 (build 5becea4c)
---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: default
- Container Runtime: containerd
- Version: v1.22.3
- Cluster Local Registry: {Host:localhost:5000 hostFromCluster: SingleName:}
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-in
- Machine: 8145878fc02ed71ef1a50ae62c4c00d0
- Repo: n2qHgzbOabs4cpiCWSL7kA==
...
```

**Comment by maximegel** [comment]
When I jump inside the minikube container, I'm unable to ping the registry at localhost:5000. Isn't ctlptl job to take care of this configuring the registry so that minikube can access it?

**Comment by lizzthabet** [comment]
@maximegel, thanks for the detailed report! i'm taking a look at your repo to see what i can reproduce. one thought (without too much digging on my end) is that this open `ctlptl` minikube issue [#180](https://github.com/tilt-dev/ctlptl/issues/180) could be related. i will follow up with more details and/or questions.

**Comment by lizzthabet** [comment]
@maximegel, can you run `minikube ssh cat /etc/containerd/config.toml` and share the `registry.mirrors` section of the config? that will help us debug whether or not your connection issues are related to the issue i linked above (which has a more in-depth walkthrough of what could be going on!).

**Comment by maximegel** [comment]
```toml
[plugins."io.containerd.grpc.v1.cri".registry.mirrors]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
          endpoint = ["https://registry-1.docker.io"]
```

Here is the full output:

```toml
version = 2
root = "/var/lib/containerd"
state = "/run/containerd"
oom_score = 0
[grpc]
  address = "/run/containerd/containerd.sock"
  uid = 0
  gid = 0
  max_recv_message_size = 16777216
  max_send_message_size = 16777216

[debug]
  address = ""
  uid = 0
  gid = 0
  level = ""

[metrics]
  address = ""
  grpc_histogram = false

[cgroup]
  path = ""

[proxy_plugins]
# fuse-overlayfs is used for rootless
[proxy_plugins."fuse-overlayfs"]
  type = "snapshot"
  address = "/run/containerd-fuse-overlayfs.sock"

[plugins]
  [plugins."io.containerd.monitor.v1.cgroups"]
    no_prometheus = false
  [plugins."io.containerd.grpc.v1.cri"]
    stream_server_address = ""
    stream_server_port = "10010"
    enable_selinux = false
    sandbox_image = "k8s.gcr.io/pause:3.5"
    stats_collect_period = 10
    enable_tls_streaming = false
    max_container_log_line_size = 16384
    restrict_oom_score_adj = false

    [plugins."io.containerd.grpc.v1.cri".containerd]
      discard_unpacked_layers = true
      snapshotter = "overlayfs"
      [plugins."io.containerd.grpc.v1.cri".containerd.default_runtime]
        runtime_type = "io.containerd.runc.v2"
      [plugins."io.containerd.grpc.v1.cri".containerd.untrusted_workload_runtime]
        runtime_type = ""
        runtime_engine = ""
        runtime_root = ""
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          runtime_type = "io.containerd.runc.v2"
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
            SystemdCgroup = false

    [plugins."io.containerd.grpc.v1.cri".cni]
      bin_dir = "/opt/cni/bin"
      conf_dir = "/etc/cni/net.mk"
      conf_template = ""
    [plugins."io.containerd.grpc.v1.cri".registry]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
          endpoint = ["https://registry-1.docker.io"]
        [plugins."io.containerd.service.v1.diff-service"]
    default = ["walking"]
  [plugins."io.containerd.gc.v1.scheduler"]
    pause_threshold = 0.02
    deletion_threshold = 0
    mutation_threshold = 100
    schedule_delay = "0s"
    startup_delay = "100ms"
```
