### ISSUE TITLE
`k8s_custom_deploy` with empty `delete_cmd` is deleted when resource is disabled and re-enabled

### ISSUE THREAD

**Issue by lizzthabet** [tilt-dev/tilt#5652]
### Expected Behavior

I'm not sure what the expected behavior is. If the user-defined delete command is solely responsible for resource cleanup in Tilt, then the current behavior seems buggy.

### Current Behavior

When a `k8s_custom_deploy` has a "empty" `delete_cmd` (like `delete_cmd="echo nothing"`), Tilt will delete the associated k8s objects when the resource is disabled and re-enabled.

[Rex Via on k8s slack](https://kubernetes.slack.com/archives/CESBL84MV/p1648765505189669) reports:
> We have some objects with a k8s_custom_deploy that overrides delete_cmd to just an echo.
> However if we disable the resource and then re-enable them the deployments are deleted the second the resource is enabled. This behavior has been consistent so far.

### Steps to Reproduce
I've been able to reproduce by creating a deployment before I start Tilt, and defining the custom deploy to reference that deployment.

maybe-bug.yml:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
  labels:
    app: express
spec:
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - name: express
          image: tilt.dev/express-app
          ports:
            - containerPort: 3000
```

Tiltfile:
```python
k8s_custom_deploy(
    "maybe-bug",
    apply_cmd="""
        kubectl -v=0 set image deployment/express *=$TILT_IMAGE_0 > /dev/null && \
 kubectl get deployment/express -o yaml
    """,
    delete_cmd="echo not deleting!",
    deps=[],
    image_deps=["tilt.dev/express-app"],
)
```

1. Run `kubectl apply -f maybe-bug.yml`
2. Disable the "maybe-bug" resource through the Tilt UI or CLI. Tilt will log:
```
Begin deleting disabled Kubernetes objects:
Running cmd: echo not deleting!
not deleting!
Resource "maybe-bug" disabled. To enable/disable it, use the Tilt Web UI.
```
3. Verify that the k8s deployment still exists
4. Re-enable the "maybe-bug" resource through the Tilt UI or CLI
5. The k8s deployment has now been deleted and the custom resource will error out after it builds.

When the resource is re-enabled, the `deployment` object is deleted as part of garbage collection (before the build begins):
```
Begin garbage collecting Kubernetes objects:
→ express:deployment
Deleting kubernetes objects:
→ Deployment/express
Resource "maybe-bug" enabled. To enable/disable it, use the Tilt Web UI.
```

#### `tilt doctor` Output

```
Tilt: v0.26.2, built 2022-03-18
System: darwin-amd64
---
Docker
- Host: [default]
- Server Version: 20.10.10
- API Version: 1.41
- Builder: 2
- Compose Version: v1.29.2 (build 5becea4c)
---
Kubernetes
- Env: kind-0.6+
- Context: kind-kind
- Cluster Name: kind-kind
- Namespace: default
- Container Runtime: containerd
- Version: v1.21.1
- Cluster Local Registry: {Host:localhost:59084 hostFromCluster: SingleName:}
```
