### ISSUE TITLE
Force update ignores `k8s_custom_deploy` `delete_cmd`

### ISSUE THREAD

**Issue by Dhouti** [tilt-dev/tilt#5722]
### Expected Behavior
Force update should respect the `delete_cmd` of custom deploys and not trigger garbage collection.

### Current Behavior
```
STEP 1/4 — Force update
     Begin force update:
     Running cmd: echo not deleting!
     not deleting!

Begin garbage collecting Kubernetes objects:
→ nginx:deployment
Deleting kubernetes objects:
→ Deployment/nginx
```

### Steps to Reproduce
<details>
  <summary>Tiltfile</summary>
  
  ```
  docker_build(
      ref="nginx-image-that-does-not-exist",
      context=".", 
       dockerfile_contents="""
          FROM nginx
      """
  )
  
  k8s_custom_deploy(
      "nginx",
      apply_cmd="""
          kubectl -v=0 set image deployment/nginx *=$TILT_IMAGE_0 > /dev/null && \
   kubectl get deployment/nginx -o yaml
      """,
      delete_cmd="echo not deleting!",
      deps=[],
      image_deps=["nginx-image-that-does-not-exist"],
  )
  ```
</details>

<details>
  <summary>deployment.yaml</summary>
  
  ```
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nginx
    labels:
      app: nginx
  spec:
    selector:
      matchLabels:
        app: nginx
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
          - name: nginx
            image: nginx-image-that-does-not-exist
            ports:
              - containerPort: 3000
  ```
</details>

1) `kubectl apply -f deployment.yaml`
2) `tilt up`
3) Trigger a forced update through the webui

#### `tilt doctor` Output
```
Tilt: v0.27.3, built 2022-04-22
System: darwin-amd64
---
Docker
- Host: [default]
- Server Version: 20.10.7
- API Version: 1.41
- Builder: 2
- Compose Version: v2.0.0-beta.4
---
Kubernetes
- Env: docker-desktop
- Context: docker-desktop
- Cluster Name: docker-desktop
- Namespace: default
- Container Runtime: docker
- Version: v1.21.2
- Cluster Local Registry: none
---
```

#### About Your Use Case
In one of my use cases for Tilt we attach to a currently running resource. We do not wish for Tilt to ever take full control over this object, we prefer being able to restrict it to only pushing new image tags.
