### ISSUE TITLE
Error applying large CRD - metadata.annotations: Too long: must have at most 262144 bytes

### ISSUE THREAD

**Issue by dev-rowbot** [tilt-dev/tilt#5860]
### Expected Behavior
When applying the `kube-prometheus-stack` helm chart I expect all resources to be created

### Current Behavior
The deployment fails because the CRD's cannot be created and this prevents the pods from being created.
The log output for `kube-prometheus-stack-crds-install` is:
```
Warning: resource customresourcedefinitions/prometheuses.monitoring.coreos.com is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
customresourcedefinition.apiextensions.k8s.io/alertmanagers.monitoring.coreos.com configured
customresourcedefinition.apiextensions.k8s.io/probes.monitoring.coreos.com configured
customresourcedefinition.apiextensions.k8s.io/podmonitors.monitoring.coreos.com configured
customresourcedefinition.apiextensions.k8s.io/prometheusrules.monitoring.coreos.com configured
customresourcedefinition.apiextensions.k8s.io/servicemonitors.monitoring.coreos.com configured
customresourcedefinition.apiextensions.k8s.io/alertmanagerconfigs.monitoring.coreos.com configured
customresourcedefinition.apiextensions.k8s.io/thanosrulers.monitoring.coreos.com configured
The CustomResourceDefinition "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

### Steps to Reproduce
Create the following files

values.yaml
```yml
prometheus:
  enabled: true
  prometheusSpec:
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 20m
        memory: 500Mi

alertmanager:
  enabled: false

grafana:
  enabled: true
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

```

Tiltfile
```py
helm_remote(
    "kube-prometheus-stack",
    repo_name="prometheus-community",
    repo_url="https://prometheus-community.github.io/helm-charts",
    values="values.yaml",
)
```

Run `tilt up`

#### `tilt doctor` Output

```
Tilt: v0.30.1, built 2022-05-20
System: linux-amd64
---
Docker
- Host: unix:///var/run/docker.sock
- Server Version: 20.10.14
- API Version: 1.41
- Builder: 2
- Compose Version: v2.6.0
---
Kubernetes
- Env: kind
- Context: kind-kind
- Cluster Name: kind-kind
- Namespace: default
- Container Runtime: containerd
- Version: v1.24.0
- Cluster Local Registry: &RegistryHosting{Host:localhost:37573,HostFromClusterNetwork:ctlptl-registry:5000,HostFromContainerRuntime:,Help:https://github.com/tilt-dev/ctlptl,SingleName:,}
```

#### About Your Use Case
I am trying to replicate a Kubernetes Dev Environment locally by deploying the same services using Tilt
