### ISSUE TITLE
Namespaces marked as duplicate

### ISSUE THREAD

**Issue by Davincible** [tilt-dev/tilt#5882]
Deploying multiple different namespaces are all seen as the same k8s entity, as they get named as `:namespace` I think.

Is there currently any way to make them unique?

I tried adding `labels.name` but has no effect.

```yaml
---
apiVersion: v1
kind: Namespace
matadata:
  name: mayastor
  labels:
    name: mayastor

```

Edit: doesn't even let me deploy the namespace with `ERROR: Build Failed: resource name may not be empty`
