### ISSUE TITLE
group services with pods

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#5886]
From sam in the tilt channel:

```
apiVersion: v1
kind: Pod
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  containers:
  - name: eureka
    image: netflixoss/eureka:1.3.1
    ports:
      - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  ports:
    - port: 8080
  selector:
    app: eureka
```

im wondering if there is any other way to flag k8s services with a label so they get grouped in tandem, like the above

Currently, Tilt will match up Services with PodTemplates (e.g., Deployments, ReplicaSets), but not with bare pods
