### ISSUE TITLE
Port forwarding doesn't work for multi-container pod

### ISSUE THREAD

**Issue by quzhi1** [tilt-dev/tilt#5905]
Let's suppose we have container a and b running on pod c. Container a exposes port 8000 and 8001, container b exposes port 5432.

### Expected Behavior
Tilt should have a way to do port forwarding for pod c on all ports: 8000, 8001, and 5432.

### Current Behavior
Tiltfile:
```
k8s_resource(
  "example-resource",
  port_forwards=['5432:5432', '8000:8000', '8001:8001']
)
```

Only port 5432 is exposed. If I call localhost:8000 or localhost:8001, I got either connection refused, or empty response EOF.

### Steps to Reproduce

Create a `developer.kong.values.yaml` file:
```yaml
env:
  database: postgres
  plugins: bundled
  untrusted_lua: "on"
  untrusted_lua_sandbox_requires: http.request, ltn12

admin:
  enabled: true
  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001
  tls:
    parameters: []

proxy:
  servicePort: 8000
  containerPort: 8000

postgresql:
  enabled: true
  auth:
    username: kong
    database: kong
    password: kong
    postgresPassword: kong

ingressController:
  enabled: true
  installCRDs: false

autoscaling:
  enabled: false
```

Deploy Kong API gateway using Tilt
```Tiltfile
# Deploy Kong
helm_repo('kong', 'https://charts.konghq.com')
helm_resource(
  'kong-kong',
  'kong/kong',
  deps=['infra/k8s/developer.kong.values.yaml'],
  flags=[
    '--set',
    'migrations.preUpgrade=false',
    '--set',
    'migrations.postUpgrade=false',
    '-f',
    'developer.kong.values.yaml',
  ],
)

# Lable Kong and port forward
k8s_resource(
  "kong-kong",
  labels="kong",
  resource_deps=[
    "license-create",
  ],
  port_forwards=['5432:5432', '8000:8000', '8001:8001']
)
```

#### `tilt doctor` Output

```
$ tilt doctor
Tilt: v0.30.5, built 2022-07-14
System: darwin-amd64
---
Docker
- Host: tcp://127.0.0.1:49896
- Server Version: 20.10.8
- API Version: 1.41
- Builder: 2
- Compose Version: v2.6.1
---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: default
- Container Runtime: docker
- Version: v1.22.3
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-out
- Machine: 5b27a5fc068a78f9550dd9a78e5ae1ae
- Repo: rVIHxbHS0Fuq+VE1YkZytQ==
```

#### About Your Use Case

We are trying to deploy Kong and forward port 5432, 8000, and 8001.
