### ISSUE TITLE
Dynamic k8s resources using gomplate

### ISSUE THREAD

**Issue by bshore** [tilt-dev/tilt#5912]
Unsure if this has been asked, or if there is a current solution for this, but I haven't found a good solution on my own just yet.

## Describe the Feature You Want

Running a `tilt up` with a `local()` or `local_resource()` ( or perhaps a new `gomplate()` function ) should allow k8s files to be templated before the `k8s_yaml(kustomize())` runs.

#### Tiltfile
```python
abs_path = os.path.dirname(__file__)
local_resource(
    'gomplate-deployment',
    abs_path+'local-k8s/gomplate.sh',
    deps=[abs_path+'/local-k8s/patch.my-resource.goyaml'],
)
# ^ will not run the gomplate.sh before k8s_yaml(), and sometimes doesn't seem to run at all?

# alternatively
#
# local(abs_path+'local-k8s/gomplate.sh')
#
# ^ runs gomplate.sh just fine, but causes the Tiltfile
# to infinitely re-run because something within '/local-k8s'
# keeps changing

# ...
# ... other stuff
# ...

k8s_yaml(kustomize('local-k8s'))
```
#### the .goyaml template
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-resource
spec:
  template:
    metadata:
      name: my-resource
    spec:
      containers:
        - name: my-resource
           image: any-image:v0.0.0
           volumeMounts:
               - name: local-files
                  mountPath: /code/files
      volumes:
        - name: local-files
           hostPath:
             path: {{ include "host_dir" }}/files
```
#### gomplate.sh
```sh
export HOST_DIR=$(pwd)
gomplate \
    -d host_dir=env:HOST_DIR
    -f $HOST_DIR/local-k8s/patch.my-resource.goyaml > $HOST_DIR/local-k8s/patch.my-resource.yaml
```
#### kustomization.yaml
```yaml
bases:
- ../k8s/my-service/base
resources:
- resource-a.yaml
- resource-b.yaml
- my-resource.yaml
patchesStrategicMerge:
- patch.my-resource.yaml # <- expected after gomplate.sh runs, the file is .gitignore-ed because the output
                         # is different from host to host ( ex: /Users/{username}/some-path-to/files )
```

### Why Do You Want This?

The reason for this, is I have a need to mount some host files into a container, and to make this reusable for my team, I'm using a `gomplate.sh` script that replaces the host path with `$(pwd)/path-to-mount` since paths will differ from machine to machine (ex: `/Users/{username}/...`)

**Additional context**
We are currently able to work around this by having the team run the `gomplate.sh` script manually before running `tilt up`, but I would think that Tilt should be able to handle this?
