### ISSUE TITLE
`tilt ci` never completes if job goes away

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#5949]
### Steps to Reproduce
Start with this project:
https://github.com/tilt-dev/tilt-example-html/tree/master/0-base

Change the tiltfile to:

```
docker_build('example-html-image', '.', entrypoint='sleep 1 && echo success')
k8s_yaml('kubernetes.yaml')
k8s_resource('example-html')
local_resource('hi', 'sleep 5', resource_deps=['example-html'])
```

Change the kubernetes yaml to:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: example-html
  labels:
    app: example-html
spec:
  ttlSecondsAfterFinished: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: example-html
        image: example-html-image
```

### Expected Behavior
`tilt ci` should notice that both jobs have succeeded and finish successfully.

### Actual behavior
The job gets cleaned up and `tilt ci` never finishes.

#### About Your Use Case
I think we need to adjust the `tilt ci` semantics for jobs so that if the Job goes away after finishing, it doesn't revert back to pending UNLESS you redeploy the job for some reason.
