### ISSUE TITLE
allowMissingKeys on k8s_kind

### ISSUE THREAD

**Issue by kossyrev-bg** [tilt-dev/tilt#5958]
## Describe the Feature You Want
I want this:
```
k8s_kind("WorkflowTemplate", image_json_path="{.spec.templates[*].container.image}")
```
to do nothing on this template:
```
# template 1
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: abc
spec:
  entrypoint: main-template
  templates:
  - name: main-template
    dag:
      tasks:
        - name: task1
          templateRef:
            name: ref1
            template: template-other
         - name: task2
           templateRef:
            name: ref2
            template: template-other
...
```
and to replace the image on this template:
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: template-other
spec:
  templates:
    - name: ref1
      container:
        command: ...
        image: some-image
    - name: ref2
      container:
        command:
          - /bin/bash
        args: ...
        image: some-image
...
```

### Current Behavior
I get 
```
finding image in WorkflowTemplate/abc: Matching (json_path="{.spec.templates[*].container.image}"): container is not found
```
because that particular template is for a dag, and so does not contain images.

### Why Do You Want This?
We use argo in our production deployments. I would like to test this in tilt by running argo workflows. Problem is, as a CRD, the workflow templates need to be defined in the Tiltfile, in order for the pods spawned by the workflow controller to have the tilt-generated images. However, as in the example above, some WorkflowTemplates do not contain that json image path.

**Additional context**
Seems like this feature may have been thought of by 
```
type JSONPath struct {
	name       string
	parser     *Parser
	stack      [][]Value // push and pop values in different scopes
	cur        []Value   // current scope values
	beginRange int
	inRange    int
	endRange   int

	allowMissingKeys bool
}
```
and yet I don't see an easy way to enable said `allowMissingKeys` from the Tiltfile API.

I would also be fine with changing the annotations/metadata on my WorkflowTemplate manifests, ie tagging some as `has_image` and others as `not_has_image`, but I don't think that will help me, since `k8s_kind` has no way of selectively ignoring `kind` objects by their annotations.
