### ISSUE TITLE
if retried job succeeds, dependent resources should start

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#5979]
### Steps to Reproduce
YAML:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: example-html
  labels:
    app: example-html
spec:
  template:
    metadata:
      labels:
        app: example-html
    spec:
      containers:
      - name: example-html
        image: example-html-image
      restartPolicy: Never
  backoffLimit: 100
```

main.sh:
```
#!/bin/bash

x="$RANDOM"
echo "Random: $x"

if [[ "$x" =~ ^[1].*$ ]]
then
    echo "starts with 1"
    exit 0
else
    echo "does not start with 1"
    exit 1
fi
```

Tiltfile:
```
docker_build('example-html-image', '.')
k8s_yaml('kubernetes.yaml')
local_resource('success', 'echo success', resource_deps=['example-html'])
```

### Expected Behavior
The `local_resource` should run when the Job succeeds

### Current Behavior
If the job fails, then succeeds, the `local_resource` is stuck pending forever. But the kubernetes resource is marked successful.
