### ISSUE TITLE
Windows Unable to view tilt snapshots

### ISSUE THREAD

**Issue by Onewaysidewalks** [tilt-dev/tilt#6024]
### Expected Behavior
On windows, running `tilt snapshot view  snapshot.json` should open (and hang) a webserver for investigative purposes

### Current Behavior
The webserver started from `tilt snapshot` immediately closes, thus the snapshot and web page can never connect/load.

### Steps to Reproduce
1. Create a tilt project with any resource (provided at end for postertity)
2. Create a snapshot of the environment
3. Run `tilt snapshot view {json file}` against the snapshot just created
4. notice that the command returns without error immediately, instead of hanging open (thus closing the webserver, instead allowing it to respond to requests)

#### Manifest to test: memcached.yaml
``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: memcached
  labels:
    app: memcached
spec:
  containers:
  - name: memcached
    image: memcached:latest
    ports:
      - containerPort: 11211
    args:
      - '-m 128'
```

#### Tiltfile
``` python
k8s_yaml('memcached.yaml')
k8s_resource('memcached')
```
#### `tilt doctor` Output
```
Tilt: v0.31.1, built 2023-01-09
System: windows-amd64
---
Docker
- Host: npipe:////./pipe/docker_engine
- Server Version: 20.10.20
- API Version: 1.41
- Builder: 2
- Compose Version: v2.12.1
---
Kubernetes
- Env: docker-desktop
- Context: docker-desktop
- Cluster Name: docker-desktop
- Namespace: default
- Container Runtime: docker
- Version: v1.25.2
- Cluster Local Registry: none
---
```
