### ISSUE TITLE
Tilt Install started failing for Docker

### ISSUE THREAD

**Issue by ScottPierce** [tilt-dev/tilt#6089]
### Expected Behavior
Docker build completes successfully.

### Current Behavior
Docker build is failing with tilt with the following error:
```
```

### Steps to Reproduce

1.
2.
3.
4.

#### `tilt doctor` Output

```
$ tilt doctor
...
```

**Comment by nicks** [comment]
thanks for reporting! I was not able to reproduce this problem. Given the steps
1) Create a dockerfile with the contents above
2) Run `docker build .`
The image built successfully.

I was even able to sh into the container and use tilt successfully:

```
docker run -it --entrypoint bash 7c7db19b1d88c1dde830bc37bce06051997bd3c67276d
root@ace9c04e007e:/# tilt version
v0.32.0, built 2023-03-13
```

Are there other steps missing?

**Comment by ScottPierce** [comment]
This is the github action that's running it. It's building it for multiple cpu archs.

```
  build-docker:
    name: Build Docker
    runs-on: [ self-hosted, docker ]
    container:
      image: scottpierce/docker:latest

    env:
      IMAGE_DOCKER: scottpierce/docker:latest
      IMAGE_TILT: scottpierce/tilt:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker
        uses: docker/build-push-action@v4
        with:
          context: docker
          target: docker
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ env.IMAGE_DOCKER }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Build Tilt
        uses: docker/build-push-action@v4
        with:
          context: docker
          target: tilt
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ env.IMAGE_TILT }}
          push: ${{ github.event_name != 'pull_request' }}
```
