### ISSUE TITLE
Behave Like Docker Compose, Given The Same Instructions File

### ISSUE THREAD

**Issue by boydingham** [tilt-dev/tilt#6220]
### Expected Behavior

If `docker compose up` successfully starts two services (_an `app` and a `db`_) specified in `docker-compose.yml`, then `tilt up` with the same instructions passed to `docker_compose(docker-compose.yml)` should successfully start both services.

### Current Behavior

Running `tilt up` with a `Tiltfile` configured with `docker_compose(docker-compose.yml)` successfully starts the `db` service but fails to start the `app` service. Tilt reports `no such service: db` for the `app` service.

### Steps to Reproduce

1. Download and extract [_this reproducer_](https://bit.ly/tilt6220Repro)
2. In the project root, run: `docker compose up`
   * Observe in the Spring Boot application logs that three entities are successfully inserted into the database:
   ```
   …
   tilt6220reproducer-app-1  | entity.Entitybus@be30
   tilt6220reproducer-app-1  | entity.Entitybus@c230
   tilt6220reproducer-app-1  | entity.Entitybus@c630
   …
   ```
3. Shut down both services with: `docker compose down`
4. Delete the Spring Boot app image with: `docker image rm tilt6220reproducer-app`
5. Still in the project root, run: `tilt up`
   * Select: `(space) to open the browser`
   * Observe that the `db` service successfully starts
   * Observe that the `app` service fails to start

#### `tilt doctor` Output

```
$ tilt doctor
Tilt: v0.33.5, built 2023-09-01

System: windows-amd64
---
Docker
- Host: npipe:////./pipe/docker_engine
- Server Version: 24.0.5
- API Version: 1.43
- Builder: 2
- Compose Version: v2.20.2-desktop.1
---
Kubernetes
- Env: 
- Context: 
- Cluster Name: Unknown
- Namespace: default
- Container Runtime: unknown
- Version: Error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-out
- Machine: e6c3ba1380e40cd27ab9920f8a492885
- Repo: O27CJq0gR9BySdsDdP/z3A==
```

#### About Your Use Case

I'm new to Tilt, but I have some experience with Docker Compose. Running stuff in Tilt that I know already works with plain Docker Compose, is my way of learning Tilt.

**Comment by boydingham** [comment]
### Workaround

1. Back in the same terminal that ran `tilt up`, do `(ctrl-c) to exit`
2. Type: `tilt down`
3. Roll back to a clean slate, with: `docker image rm tilt6220reproducer-app`
4. Edit the original `docker-compose.yml` file to be:

**Comment by nicks** [comment]
thanks for the report! 

what's the exact error message you're seeing? is it something like:

```
no such service: db
```

i think this might end up being a docker compose bug around `volumes_from`...does it work correctly if you define the volumes explicitly? something like:

```
services:
  app:
    volumes:
      - db-data:/var/lib/mysql
      - ./db-init-scripts:/docker-entrypoint-initdb.d
  db:
    volumes:
      - db-data:/var/lib/mysql
      - ./db-init-scripts:/docker-entrypoint-initdb.d

volumes:
  db-data:
```

**Comment by nicks** [comment]
filed as https://github.com/docker/compose/issues/10996

**Comment by boydingham** [comment]
> &hellip;_thanks for the report!_&hellip;

You're welcome! Thank _you_ for such a neat tool!

Your feedback on the _**Expected Behavior**_ section would be super, super valuable (_and gratefully appreciated_).

TIA.

> &hellip;_something like_&hellip;

I haven't tried your workaround specifically. I trust you that Tilt correctly processes your compose file, though.

I can also confirm that Tilt processes this different compose file successfully&hellip;

```
version: "2.1"

networks:
  test:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test
    command: java -Djava.security.egd=file:/dev/./urandom -jar /project/target/demo-0.0.0.0.jar

  db:
    image: mysql:5.7.37
    container_name: db
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DOCKERDB
    command: [
      '--default-authentication-plugin=mysql_native_password',
      '--lower-case-table-names=1'
    ]
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
          test: ["CMD", "mysql", "-h", "localhost", "-P", "3306", "-u", "root", "--password=root", "-e", "select 1", "DOCKERDB"]
          interval: 1s
          timeout: 3s
          retries: 30
    networks:
      - test
```
Another workaround that Tilt succeeded on (_I think_), was swapping the order of the service definitions in the compose file. But I haven't been able to reproduce that success a second time.

> &hellip;_define the volumes explicitly?_ 

As a side note, [_the MySQL image_](https://bit.ly/volVarLibMySQL) already provides that `/var/lib/mysql` [_volume out of the box_](https://bit.ly/volVarLibMySQL).
