### ISSUE TITLE
docker_compose(["first-compose.yml, second-compose.yml"]) mounts the volume of second docker-compose in that of the directory of the first

### ISSUE THREAD

**Issue by Hodacco** [tilt-dev/tilt#6260]
### Expected Behavior
When using the 
```
docker_compose(["path/to/api1/docker-compose.yml", "path2/to/api2/docker-compose.yml"])
```

And using almost similar docker-compose.yml like this for both APIs:
```
services:
  api1:
    image: api1
    build:
      context: path/to/api1
      dockerfile: ./Dockerfile
    env_file:
      - path/to/api1/.env
    ports:
      - 3000:3000
    networks:
      - api1-network
    volumes:
      - ./storage:/app/storage
``` 
When api1 creates a file inside /app/storage it will appear in path/to/api1/storage

When api2 creates a file inside /app/storage it will appear in path/to/api2/storage

### Current Behavior
The volume that has been mounted in **api2** is that of **api1** and not **api2**
That means that when api2 creates a file in app/storage of its volume, it will appear in path/to/api1/storage instead.

### Steps to Reproduce
Start up two docker-compose.yml with mounted volumes in their own separate folders. Start them with the following tiltfile

Tiltfile:
```
docker_compose(["api1/docker-compose.yml", "api2/docker-compose.yml"])
```

#### `tilt doctor` Output

```
Tilt: v0.33.6, built 2023-09-29
System: darwin-arm64
---
Docker
- Host: unix:///Users/dacbaolong.ho/.colima/docker.sock
- Server Version: 23.0.6
- API Version: 1.42
- Builder: 2
- Compose Version: v2.23.0
---
Kubernetes
- Env: colima
- Context: colima
- Cluster Name: colima
- Namespace: default
- Container Runtime: docker
- Version: v1.27.3+k3s1
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-out
- Machine: b41e1f9d3fca4a04564c8dcab4acdad1
- Repo: EoiF+1I2oIWl5BIHz8brfg==
```

#### About Your Use Case
I want separate Volumes for my applications. they are similar in build, but the files needed to mount and that are created are entirely different.
