### ISSUE TITLE
Installing Tilt in GitHub Actions results in Error

### ISSUE THREAD

**Issue by samcat116** [tilt-dev/tilt#6267]
### Expected Behavior
Tilt should be installed on the Github action runner to be able to run `tilt ci`.

### Current Behavior
Running `tilt ci` as a step in a workflow results in:

```
Tilt started on http://localhost:10350/
v0.33.7, built 2023-11-29
Tilt analytics disabled: Environment variable CI=true
Error: running in prod mode, but JS/CSS files are not available.
Please report this: https://github.com/tilt-dev/tilt/issues
Error: Process completed with exit code 1.
```

### Steps to Reproduce
Here's the GHA I am running:
```
name: Kube CI
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install K8s
        run: curl -sfL https://get.k3s.io | sh -
      - name: Install Tilt
        run: curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | bash
      - name: Run Tilt CI
        run: tilt ci
```

#### `tilt doctor` Output
Can't run `tilt doctor` as this is in an ephemeral GHA runner

#### About Your Use Case
I haven't seen a prebuilt GitHub action to use for this, but let me know if there is a better way to use tilt in that environment. I am also spinning up K3s on the same runner.
