### ISSUE TITLE
livenessProbeProbe returns Connection Refused

### ISSUE THREAD

**Issue by NileshMSD** [tilt-dev/tilt#6347]
### Expected Behavior
The API used to check for livenessProbeProbe must return a `200 OK`.

### Current Behavior
```
[event: pod dev-nilesh/vuex-backend-prototyping-dev-56df545fc8-7fjrh] Liveness probe failed: Get "[http://10.51.230.85:8000/api/v1/ping":](http://10.51.230.85:8000/api/v1/ping:) dial tcp 10.51.230.85:8000: connect: connection refused
```

### Steps to Reproduce

1. Add a simple `livenessProbe` to your .yaml file. Here is a sample
```
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /api/v1/ping
    port: 8000
    scheme: HTTP
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10
```
2. Perform a `tilt up`.

#### `tilt doctor` Output
```
$ tilt doctor

Tilt: v0.33.11, built 2024-02-15
System: darwin-arm64
---
Docker
- Host: unix:///Users/nilesh/.colima/default/docker.sock
- Server Version: 24.0.7
- API Version: 1.43
- Builder: 2
---
Kubernetes
- Env: eks
- Context: arn:aws:eks:us-east-1:742927057462:cluster/blox-dev-internal-use1-eks
- Cluster Name: arn:aws:eks:us-east-1:742927057462:cluster/blox-dev-internal-use1-eks
- Namespace: default
- Container Runtime: containerd
- Version: v1.27.10-eks-508b6b3
- Cluster Local Registry: none
---
...
```

#### About Your Use Case
I am trying to set up readinessProbe and livenessProbe for my app, and unable to do so due to the above-described issue. I would appreciate any help on how to debug this issue. Many thanks for considering my request. I feel like the fix for this is something silly but I still haven't found a solution on your docs.
