### ISSUE TITLE
Service with selector not recognized

### ISSUE THREAD

**Issue by bittermandel** [tilt-dev/tilt#6404]
### Expected Behavior
I expect the k8s service to be created and managed by Tilt as intended.

### Current Behavior
Unless I change either the key or the value of the selector, Tilt ignores the file.

### Steps to Reproduce
This is the Service I'm targetting:
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: temporal-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
```

#### `tilt doctor` Output

```
$ tilt doctor
Tilt: v0.33.17, built 2024-06-12
System: linux-amd64
---
Docker
- Host: unix:///var/run/docker.sock
- Server Version: 24.0.7
- API Version: 1.43
- Builder: 2
- Compose Version: v2.27.0
---
Kubernetes
- Env: kind
- Context: kind-molnett
- Cluster Name: kind-molnett
- Namespace: default
- Container Runtime: containerd
- Version: v1.30.0
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-in
- Machine: 0f229b09995c2721819417b9cf1b51bc
- Repo: rqGPZYxzrdJ/vT+5WBItoQ==
...
```

#### About Your Use Case
This blocks us from using Tilt to fully replicate our local environment.
