### ISSUE TITLE
docker_build should support custom path

### ISSUE THREAD

**Issue by XBeg9** [tilt-dev/tilt#6448]
### Expected Behavior
docker_build accept additional paths to search for image injection

### Current Behavior
in my case I have a CRD that accepts image in this path `spec.image`, and Tilt complains about it 
```
Image not used in any Kubernetes config:
    ✕ kafkaconnect
```

### Steps to Reproduce
Sample CRD

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: connector
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  image: kafkaconnect
  replicas: 1
  bootstrapServers: "kafka-kafka-bootstrap:9093"
  authentication:
    type: scram-sha-512
    username: kafkauser
    passwordSecret:
      secretName: kafkauser-secret
      password: password
  config:
    group.id: connector-cluster
    offset.storage.topic: connector-offsets
    config.storage.topic: connector-configs
    status.storage.topic: connector-status
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
```

**Comment by XBeg9** [comment]
My current workaround is something like this:

1. make a fake job, so docker build is going to happen (tag can be found by `spec.template.spec.containers.image` path

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: no-op
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: no-op
        image: kafkaconnect
      restartPolicy: Never
```

2. do additional tag (extra_tag is not going to push anything, unless it can find the tag again in `yaml`)

```
custom_build('kafkaconnect', 'docker build -t $EXPECTED_REF -t localhost:5005/kafkaconnect:latest k8s/kafka/connector', ['.'])
```

3. use that image `image: localhost:5005/kafkaconnect:latest`
