### ISSUE TITLE
Tilt gets stuck on docker builds over time.

### ISSUE THREAD

**Issue by hookenz** [tilt-dev/tilt#6521]
### Expected Behavior
Sync files or rebuild and stop

### Current Behavior
Over time, the docker build or sync fails and Tilt is stuck.
Stopping Tilt and restarting it fixes the problem.  

### Steps to Reproduce
This is my Tiltfile.

```
docker_build('serverkit', '.', dockerfile="docker/frankenphp/Dockerfile", live_update=[
    sync('./server', '/app/www/server'),
    sync('./scripts', '/app/www/scripts'),
])

docker_compose('docker-compose.yaml')
```

And my docker-compose.yaml contains

```
services:
    serverkit:
        image: serverkit:latest
        ports:
            - '8080:8080'
        environment:
            XDEBUG_SESSION: "1"
            XDEBUG_MODE: "debug"
            XDEBUG_CONFIG: "client_host=172.17.0.1"
        volumes:
           - serverkit:/app/www

volumes:
   serverkit:

```

There is nothing very special about the Docker build.  However the I'm using the local docker build and no actual registry.   It works perfectly until it doesn't which is every day after about 1/2 an hour or 1 hr.
I notice that my changes stop being reflected.  I go to the tilt web page and notice that it's stuck updating.
I kill tilt and restart it and then it's good again.

#### `tilt doctor` Output

Note: I have a local kube cluster but I'm not using it right now.

```
> tilt doctor
Tilt: v0.33.22, built 2025-01-03
System: linux-amd64
---
Docker
- Host: unix:///var/run/docker.sock
- Server Version: 27.5.1
- API Version: 1.47
- Builder: 2
- Compose Version: v2.32.4
---
Kubernetes
- Env: microk8s
- Context: microk8s
- Cluster Name: microk8s-cluster
- Namespace: default
- Container Runtime: containerd
- Version: v1.31.6
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-in
- Machine: a7f8b6b7a4409acf726e04e4bfe16333
- Repo: uzIf4DZfcR098uK3ZYGRbA==

...
```

#### About Your Use Case
I'm developing a PHP application using Tilt and Docker Engine under Linux.
However, I have no local registry so I'm just using the local Docker image
